### ISSUE TITLE
Video URLs no longer compatilble

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Twitch.bundle#2]
The channel gives a URL service pattern error for every video you try to access. But would need to look deeper to see if it is a URL Service pattern issue or just an issue with the video URL pull.

**Comment by sander1** [comment]
Fixed in https://github.com/plexinc-plugins/Services.bundle/commit/54e2b1c7d34ad8a98bb77fef50c9474e49144e9f
