### ISSUE TITLE
Past broadcasts don't work

### ISSUE THREAD

**Issue by dreamtheme** [plexinc-plugins/Twitch.bundle#6]
On the latest version Past broadcasts and Highlights don't work, when i load them, nothing appears (only more.. button).

**Comment by sander1** [comment]
Those options are not in this version of the channel. You're probably using TwitchMod: https://github.com/coryo/TwitchMod.bundle That repo does not have an issue tracker, but you can report issues in the forum post here: https://forums.plex.tv/discussion/178235/rel-twitchmod-twitch-tv-with-extra-features/p1

**Comment by dreamtheme** [comment]
I have but no one respond. thanks anyway.
